sudo: required
dist: xenial
group: travis_latest
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

cache:
  directories:
    - $HOME/.bazel-output-base
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          packages:
          - g++-5
      env:
        - CXX_COMPILER="g++-5"
        - C_COMPILER="gcc-5"
    - os: osx
      osx_image: xcode9.2  # macOS-10.12
      compiler: clang
      env:
        - CXX_COMPILER="clang++"
        - C_COMPILER="clang"
    - os: osx
      osx_image: xcode9.4  # macOS-10.13
      compiler: clang
      env:
        - CXX_COMPILER="clang++"
        - C_COMPILER="clang"
    - os: osx
      osx_image: xcode10.2  # macOS-10.14
      compiler: clang
      env:
        - CXX_COMPILER="clang++"
        - C_COMPILER="clang"

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      curl -s https://raw.githubusercontent.com/dreal/dreal4/master/setup/ubuntu/update_expired_keys.sh | sudo bash;
      curl -s https://raw.githubusercontent.com/dreal/dreal4/master/setup/ubuntu/16.04/install.sh | sudo bash;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew tap dreal/dreal;
      brew update;
      brew install dreal/dreal/dreal || true;
    fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} ../
  - make           
  - ./check_sat

notifications:
  recipients:
    - soonho.kong@gmail.com
  email:
    on_success: change
    on_failure: always
